sonar.projectKey=frontend
sonar.projectName=Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,src/environments/**
sonar.tests=src
sonar.test.inclusion=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
