FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY backend/formateur-service/target/formateur-service-3.2.5.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-XX:TieredStopAtLevel=1", "-XX:+UseSerialGC", "-Xmx384m", "-jar", "app.jar"]
