apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: plateforme
type: Opaque
# Les valeurs sont en base64 — générer avec :
#   echo -n "votre_valeur" | base64
stringData:
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: changeme_strong_password
  KEYCLOAK_ISSUER_URI: https://auth.votredomaine.com/realms/plateforme
